### PR TITLE
Support public key

### PR DESCRIPTION
**Pull request by riemannulus**
Hi

First of all, thanks for your work. It is a great project.
but when I use this library, I need not only an address but also a public key.
So, I made this PR to support the public key too.
Please review this and I hope this commit would be merged.

### CODE REVIEW

**Comment by odanado** [comment]
Thanks for the pull-request.
I think this is a good change.

**Comment by odanado** [comment]
When it receives a pull request from a human, CI don't run #255

So, I ran `yarn test` in local and was successed the command.

**Review by odanado — APPROVED** [review]
LGTM

**Comment by odanado** [comment]
Released https://github.com/odanado/aws-kms-provider/releases/tag/v0.3.3

**Comment by riemannulus** [comment]
Thanks for the fast response!

**Pull request merged**
